// Code generated by protoc-gen-go. DO NOT EDIT.
// source: card.proto

package protomodels

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Language int32

const (
	Language_ENGLISH  Language = 0
	Language_JAPANESE Language = 1
	Language_FRENCH   Language = 2
)

var Language_name = map[int32]string{
	0: "ENGLISH",
	1: "JAPANESE",
	2: "FRENCH",
}

var Language_value = map[string]int32{
	"ENGLISH":  0,
	"JAPANESE": 1,
	"FRENCH":   2,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}

func (Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_95fd8cb6caa913ee, []int{0}
}

type AssociationTypes int32

const (
	AssociationTypes_SYNONYMS           AssociationTypes = 0
	AssociationTypes_ANTONYMS           AssociationTypes = 1
	AssociationTypes_ORIGIN             AssociationTypes = 2
	AssociationTypes_DERIVATIVES        AssociationTypes = 3
	AssociationTypes_IN_OTHER_LANGUAGES AssociationTypes = 4
	AssociationTypes_OTHERS             AssociationTypes = 5
)

var AssociationTypes_name = map[int32]string{
	0: "SYNONYMS",
	1: "ANTONYMS",
	2: "ORIGIN",
	3: "DERIVATIVES",
	4: "IN_OTHER_LANGUAGES",
	5: "OTHERS",
}

var AssociationTypes_value = map[string]int32{
	"SYNONYMS":           0,
	"ANTONYMS":           1,
	"ORIGIN":             2,
	"DERIVATIVES":        3,
	"IN_OTHER_LANGUAGES": 4,
	"OTHERS":             5,
}

func (x AssociationTypes) String() string {
	return proto.EnumName(AssociationTypes_name, int32(x))
}

func (AssociationTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_95fd8cb6caa913ee, []int{1}
}

type Card struct {
	Index            *CardIndex `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Labels           []string   `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Explanations     []string   `protobuf:"bytes,3,rep,name=explanations,proto3" json:"explanations,omitempty"`
	ExampleSentences []string   `protobuf:"bytes,4,rep,name=example_sentences,json=exampleSentences,proto3" json:"example_sentences,omitempty"`
	// where 0 means not familiar at all, 10 means very familiar
	Familiarity          int32                `protobuf:"varint,5,opt,name=familiarity,proto3" json:"familiarity,omitempty"`
	ReviewDate           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=review_date,json=reviewDate,proto3" json:"review_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_95fd8cb6caa913ee, []int{0}
}

func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (m *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(m, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetIndex() *CardIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *Card) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Card) GetExplanations() []string {
	if m != nil {
		return m.Explanations
	}
	return nil
}

func (m *Card) GetExampleSentences() []string {
	if m != nil {
		return m.ExampleSentences
	}
	return nil
}

func (m *Card) GetFamiliarity() int32 {
	if m != nil {
		return m.Familiarity
	}
	return 0
}

func (m *Card) GetReviewDate() *timestamp.Timestamp {
	if m != nil {
		return m.ReviewDate
	}
	return nil
}

type RelatedCards struct {
	Index                *CardIndex   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Synonyms             []*CardIndex `protobuf:"bytes,2,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	Antonyms             []*CardIndex `protobuf:"bytes,3,rep,name=antonyms,proto3" json:"antonyms,omitempty"`
	Origin               *CardIndex   `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	Derivatives          []*CardIndex `protobuf:"bytes,5,rep,name=derivatives,proto3" json:"derivatives,omitempty"`
	InOtherLanguages     []*CardIndex `protobuf:"bytes,6,rep,name=in_other_languages,json=inOtherLanguages,proto3" json:"in_other_languages,omitempty"`
	Others               []*CardIndex `protobuf:"bytes,7,rep,name=others,proto3" json:"others,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RelatedCards) Reset()         { *m = RelatedCards{} }
func (m *RelatedCards) String() string { return proto.CompactTextString(m) }
func (*RelatedCards) ProtoMessage()    {}
func (*RelatedCards) Descriptor() ([]byte, []int) {
	return fileDescriptor_95fd8cb6caa913ee, []int{1}
}

func (m *RelatedCards) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelatedCards.Unmarshal(m, b)
}
func (m *RelatedCards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelatedCards.Marshal(b, m, deterministic)
}
func (m *RelatedCards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelatedCards.Merge(m, src)
}
func (m *RelatedCards) XXX_Size() int {
	return xxx_messageInfo_RelatedCards.Size(m)
}
func (m *RelatedCards) XXX_DiscardUnknown() {
	xxx_messageInfo_RelatedCards.DiscardUnknown(m)
}

var xxx_messageInfo_RelatedCards proto.InternalMessageInfo

func (m *RelatedCards) GetIndex() *CardIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *RelatedCards) GetSynonyms() []*CardIndex {
	if m != nil {
		return m.Synonyms
	}
	return nil
}

func (m *RelatedCards) GetAntonyms() []*CardIndex {
	if m != nil {
		return m.Antonyms
	}
	return nil
}

func (m *RelatedCards) GetOrigin() *CardIndex {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *RelatedCards) GetDerivatives() []*CardIndex {
	if m != nil {
		return m.Derivatives
	}
	return nil
}

func (m *RelatedCards) GetInOtherLanguages() []*CardIndex {
	if m != nil {
		return m.InOtherLanguages
	}
	return nil
}

func (m *RelatedCards) GetOthers() []*CardIndex {
	if m != nil {
		return m.Others
	}
	return nil
}

type CardIndex struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Language             Language `protobuf:"varint,2,opt,name=language,proto3,enum=protomodels.Language" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardIndex) Reset()         { *m = CardIndex{} }
func (m *CardIndex) String() string { return proto.CompactTextString(m) }
func (*CardIndex) ProtoMessage()    {}
func (*CardIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_95fd8cb6caa913ee, []int{2}
}

func (m *CardIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardIndex.Unmarshal(m, b)
}
func (m *CardIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardIndex.Marshal(b, m, deterministic)
}
func (m *CardIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardIndex.Merge(m, src)
}
func (m *CardIndex) XXX_Size() int {
	return xxx_messageInfo_CardIndex.Size(m)
}
func (m *CardIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_CardIndex.DiscardUnknown(m)
}

var xxx_messageInfo_CardIndex proto.InternalMessageInfo

func (m *CardIndex) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CardIndex) GetLanguage() Language {
	if m != nil {
		return m.Language
	}
	return Language_ENGLISH
}

func init() {
	proto.RegisterEnum("protomodels.Language", Language_name, Language_value)
	proto.RegisterEnum("protomodels.AssociationTypes", AssociationTypes_name, AssociationTypes_value)
	proto.RegisterType((*Card)(nil), "protomodels.Card")
	proto.RegisterType((*RelatedCards)(nil), "protomodels.RelatedCards")
	proto.RegisterType((*CardIndex)(nil), "protomodels.CardIndex")
}

func init() { proto.RegisterFile("card.proto", fileDescriptor_95fd8cb6caa913ee) }

var fileDescriptor_95fd8cb6caa913ee = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x6f, 0xda, 0x4e,
	0x10, 0xc5, 0xbf, 0xe6, 0x87, 0x03, 0x63, 0xf4, 0xad, 0xbb, 0x52, 0x91, 0x95, 0x4b, 0x11, 0x27,
	0x94, 0x56, 0x8e, 0x42, 0x2f, 0x95, 0x7a, 0xb2, 0x82, 0x0b, 0xae, 0xa8, 0xa9, 0xd6, 0x34, 0x52,
	0x4e, 0xd6, 0x82, 0x27, 0x74, 0x25, 0x7b, 0x8d, 0xbc, 0x1b, 0x0a, 0xf7, 0xfe, 0xd9, 0x3d, 0x54,
	0x5e, 0x63, 0x44, 0x0e, 0x45, 0xea, 0xc9, 0xde, 0x37, 0x9f, 0x37, 0x3b, 0x6f, 0x6c, 0x80, 0x35,
	0x2b, 0x12, 0x77, 0x5b, 0xe4, 0x2a, 0x27, 0x96, 0x7e, 0x64, 0x79, 0x82, 0xa9, 0xbc, 0x7e, 0xbb,
	0xc9, 0xf3, 0x4d, 0x8a, 0xb7, 0x5a, 0x5b, 0x3d, 0x3f, 0xdd, 0x2a, 0x9e, 0xa1, 0x54, 0x2c, 0xdb,
	0x56, 0xf4, 0xf0, 0xb7, 0x01, 0xad, 0x7b, 0x56, 0x24, 0xe4, 0x3d, 0xb4, 0xb9, 0x48, 0x70, 0xef,
	0x18, 0x03, 0x63, 0x64, 0x8d, 0xfb, 0xee, 0x59, 0x1b, 0xb7, 0x24, 0x82, 0xb2, 0x4a, 0x2b, 0x88,
	0xf4, 0xc1, 0x4c, 0xd9, 0x0a, 0x53, 0xe9, 0x34, 0x06, 0xcd, 0x51, 0x97, 0x1e, 0x4f, 0x64, 0x08,
	0x3d, 0xdc, 0x6f, 0x53, 0x26, 0x98, 0xe2, 0xb9, 0x90, 0x4e, 0x53, 0x57, 0x5f, 0x68, 0xe4, 0x1d,
	0xbc, 0xc6, 0x3d, 0xcb, 0xb6, 0x29, 0xc6, 0x12, 0x85, 0x42, 0xb1, 0x46, 0xe9, 0xb4, 0x34, 0x68,
	0x1f, 0x0b, 0x51, 0xad, 0x93, 0x01, 0x58, 0x4f, 0x2c, 0xe3, 0x29, 0x67, 0x05, 0x57, 0x07, 0xa7,
	0x3d, 0x30, 0x46, 0x6d, 0x7a, 0x2e, 0x91, 0x4f, 0x60, 0x15, 0xb8, 0xe3, 0xf8, 0x33, 0x4e, 0x98,
	0x42, 0xc7, 0xd4, 0xe3, 0x5f, 0xbb, 0x55, 0x70, 0xb7, 0x0e, 0xee, 0x2e, 0xeb, 0xe0, 0x14, 0x2a,
	0x7c, 0xc2, 0x14, 0x0e, 0x7f, 0x35, 0xa1, 0x47, 0x31, 0x65, 0x0a, 0x93, 0x32, 0xa3, 0xfc, 0xc7,
	0x35, 0x8c, 0xa1, 0x23, 0x0f, 0x22, 0x17, 0x87, 0xac, 0x5a, 0xc4, 0xdf, 0x0d, 0x27, 0xae, 0xf4,
	0x30, 0xa1, 0x2a, 0x4f, 0xf3, 0xb2, 0xa7, 0xe6, 0x88, 0x0b, 0x66, 0x5e, 0xf0, 0x0d, 0x17, 0x4e,
	0xeb, 0xe2, 0x58, 0x47, 0x8a, 0x7c, 0x04, 0x2b, 0xc1, 0x82, 0xef, 0x98, 0xe2, 0x3b, 0x94, 0x4e,
	0xfb, 0xe2, 0x35, 0xe7, 0x28, 0x99, 0x00, 0xe1, 0x22, 0xce, 0xd5, 0x0f, 0x2c, 0xe2, 0x94, 0x89,
	0xcd, 0x33, 0xdb, 0xa0, 0x74, 0xcc, 0x8b, 0x0d, 0x6c, 0x2e, 0x16, 0xa5, 0x61, 0x5e, 0xf3, 0x7a,
	0xde, 0x52, 0x91, 0xce, 0xd5, 0x45, 0xe7, 0x91, 0x1a, 0x52, 0xe8, 0x9e, 0x44, 0x42, 0xa0, 0x25,
	0x58, 0x86, 0xfa, 0x0b, 0x74, 0xa9, 0x7e, 0x27, 0x77, 0xd0, 0xa9, 0xa7, 0x71, 0x1a, 0x03, 0x63,
	0xf4, 0xff, 0xf8, 0xcd, 0x8b, 0x96, 0xf5, 0xd5, 0xf4, 0x84, 0xdd, 0xdc, 0x41, 0xa7, 0x56, 0x89,
	0x05, 0x57, 0x7e, 0x38, 0x9d, 0x07, 0xd1, 0xcc, 0xfe, 0x8f, 0xf4, 0xa0, 0xf3, 0xc5, 0xfb, 0xe6,
	0x85, 0x7e, 0xe4, 0xdb, 0x06, 0x01, 0x30, 0x3f, 0x53, 0x3f, 0xbc, 0x9f, 0xd9, 0x8d, 0x9b, 0x1c,
	0x6c, 0x4f, 0xca, 0x7c, 0xcd, 0xf5, 0x9f, 0xba, 0x3c, 0x6c, 0x51, 0x96, 0x74, 0xf4, 0x18, 0x2e,
	0xc2, 0xc7, 0xaf, 0x51, 0xe5, 0xf5, 0xc2, 0x65, 0x75, 0xd2, 0xde, 0x05, 0x0d, 0xa6, 0x41, 0x68,
	0x37, 0xc8, 0x2b, 0xb0, 0x26, 0x3e, 0x0d, 0x1e, 0xbc, 0x65, 0xf0, 0xe0, 0x47, 0x76, 0x93, 0xf4,
	0x81, 0x04, 0x61, 0xbc, 0x58, 0xce, 0x7c, 0x1a, 0xcf, 0xbd, 0x70, 0xfa, 0xdd, 0x9b, 0xfa, 0x91,
	0xdd, 0xd2, 0xa6, 0x52, 0x8c, 0xec, 0xf6, 0xca, 0xd4, 0x19, 0x3e, 0xfc, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x9a, 0x5c, 0xac, 0x20, 0xc0, 0x03, 0x00, 0x00,
}
