// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package protomodels

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Log struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	ReviewCards          int32    `protobuf:"varint,2,opt,name=review_cards,json=reviewCards,proto3" json:"review_cards,omitempty"`
	NewCards             int32    `protobuf:"varint,3,opt,name=new_cards,json=newCards,proto3" json:"new_cards,omitempty"`
	Streak               int32    `protobuf:"varint,4,opt,name=streak,proto3" json:"streak,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Log) GetReviewCards() int32 {
	if m != nil {
		return m.ReviewCards
	}
	return 0
}

func (m *Log) GetNewCards() int32 {
	if m != nil {
		return m.NewCards
	}
	return 0
}

func (m *Log) GetStreak() int32 {
	if m != nil {
		return m.Streak
	}
	return 0
}

func init() {
	proto.RegisterType((*Log)(nil), "protomodels.Log")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886) }

var fileDescriptor_a153da538f858886 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0xc9, 0x4f, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x06, 0x53, 0xb9, 0xf9, 0x29, 0xa9, 0x39, 0xc5, 0x4a,
	0x85, 0x5c, 0xcc, 0x3e, 0xf9, 0xe9, 0x42, 0x42, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0xa9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x22, 0x17, 0x4f, 0x51, 0x6a, 0x59, 0x66, 0x6a,
	0x79, 0x7c, 0x72, 0x62, 0x51, 0x4a, 0xb1, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x37, 0x44,
	0xcc, 0x19, 0x24, 0x24, 0x24, 0xcd, 0xc5, 0x99, 0x07, 0x97, 0x67, 0x06, 0xcb, 0x73, 0xe4, 0xc1,
	0x24, 0xc5, 0xb8, 0xd8, 0x8a, 0x4b, 0x8a, 0x52, 0x13, 0xb3, 0x25, 0x58, 0xc0, 0x32, 0x50, 0x5e,
	0x12, 0x1b, 0xd8, 0x7e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xc1, 0xf4, 0xce, 0x93,
	0x00, 0x00, 0x00,
}
