swagger: "2.0"
info:
  title: Card API
  version: 1.0.0
host: localhost:8080
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /card/create:
    post:
      summary: Create a new card
      operationId: createCard
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              card:
                type: object
                properties:
                  name:
                    type: string
                  number:
                    type: string
                  cvv:
                    type: string
                  expiry_date:
                    type: string
                  billing_address:
                    type: object
                    properties:
                      street:
                        type: string
                      city:
                        type: string
                      state:
                        type: string
                      zip:
                        type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
                  amount:
                    type: number
                  currency:
                    type: string
      responses:
        '200':
          description: Card created successfully
        '400':
          description: Invalid input
