swagger: "2.0"
info:
  title: "Card API"
  version: "1.0.0"
paths:
  /card:
    post:
      summary: "Create a new card"
      parameters:
        - name: "card"
          in: "body"
          description: "Card object that needs to be added to the database"
          required: true
          schema:
            $ref: "#/definitions/Card"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Card"
        "400":
          description: "Bad Request"
definitions:
  Card:
    type: "object"
    properties:
      index:
        $ref: "#/definitions/CardIndex"
      labels:
        type: "array"
        items:
          type: "string"
      explanations:
        type: "array"
        items:
          type: "string"
      example_sentences:
        type: "array"
        items:
          type: "string"
      familiarity:
        type: "integer"
        format: "int32"
      review_date:
        type: "string"
  CardIndex:
    type: "object"
    properties:
      name:
        type: "string"
      language:
        type: "string"
