openapi: 3.0.0
info:
  title: Langdida Server API
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
paths:
  /exercise/choice:
    post:
      summary: Create choice problems
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CardIndex'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  problems:
                    type: array
                    items:
                      $ref: '#/components/schemas/Problem'
                  answers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Answer'
        '400':
          description: Bad request

  /exercise/filling:
    post:
      summary: Create filling problems
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CardIndex'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  problems:
                    type: array
                    items:
                      $ref: '#/components/schemas/Problem'
                  answers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Answer'
        '400':
          description: Bad request

  /card/create:
    post:
      summary: Create a new card
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Card'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example: OK
        '400':
          description: Bad request

  /card/edit:
    post:
      summary: Edit an existing card
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Card'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example: OK
        '400':
          description: Bad request

  /card/get:
    get:
      summary: Get a card by language and word
      parameters:
        - name: language
          in: query
          required: true
          schema:
            type: string
          description: Language code (e.g., en, jp, fr)
        - name: word
          in: query
          required: true
          schema:
            type: string
          description: Word to search for
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        '400':
          description: Bad request

components:
  schemas:
    Card:
      type: "object"
      properties:
        index:
          $ref: "#/components/schemas/CardIndex"
        labels:
          type: "array"
          items:
            type: "string"
        explanations:
          type: "array"
          items:
            type: "string"
        example_sentences:
          type: "array"
          items:
            type: "string"
        familiarity:
          type: "integer"
          format: "int32"
        review_date:
          type: "string"
    CardIndex:
      type: "object"
      properties:
        name:
          type: "string"
        language:
          type: "string"

    Problem:
      type: array
      items:
        type: string

    Answer:
      type: array
      items:
        type: string
