name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build for Windows x64
        run: GOOS=windows GOARCH=amd64 go build -o langdida-server-windows-x64.exe

      - name: Build for Windows x86
        run: GOOS=windows GOARCH=386 go build -o langdida-server-windows-x86.exe

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o langdida-server-linux

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Windows x64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./langdida-server-windows-x64.exe
          asset_name: langdida-server-windows-x64.exe
          asset_content_type: application/octet-stream

      - name: Upload Windows x86 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./langdida-server-windows-x86.exe
          asset_name: langdida-server-windows-x86.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./langdida-server-linux
          asset_name: langdida-server-linux
          asset_content_type: application/octet-stream